/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as PrototypingToProductionRouteImport } from './routes/prototyping-to-production'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FactoryRouteImport } from './routes/factory'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as MaterialsIndexRouteImport } from './routes/materials.index'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as ServicesWireEdmRouteImport } from './routes/services.wire-edm'
import { Route as ServicesToolAndDieRouteImport } from './routes/services.tool-and-die'
import { Route as ServicesSurfaceGrindingRouteImport } from './routes/services.surface-grinding'
import { Route as ServicesReverseEngineeringRouteImport } from './routes/services.reverse-engineering'
import { Route as ServicesRapidPrototypingRouteImport } from './routes/services.rapid-prototyping'
import { Route as ServicesProductionRouteImport } from './routes/services.production'
import { Route as ServicesProductDevelopmentRouteImport } from './routes/services.product-development'
import { Route as ServicesPrecisionComponentsRouteImport } from './routes/services.precision-components'
import { Route as ServicesPlasticInjectionMoldingRouteImport } from './routes/services.plastic-injection-molding'
import { Route as ServicesLedLightsRouteImport } from './routes/services.led-lights'
import { Route as ServicesInjectionMoldManufacturingRouteImport } from './routes/services.injection-mold-manufacturing'
import { Route as ServicesDieCastingRouteImport } from './routes/services.die-casting'
import { Route as ServicesCustomManufacturingRouteImport } from './routes/services.custom-manufacturing'
import { Route as ServicesCncMachiningRouteImport } from './routes/services.cnc-machining'
import { Route as ServicesCadCamDesignRouteImport } from './routes/services.cad-cam-design'
import { Route as Services3dScanningRouteImport } from './routes/services.3d-scanning'
import { Route as ResourcesProductLifeCycleRouteImport } from './routes/resources.product-life-cycle'
import { Route as ResourcesDesignTipsRouteImport } from './routes/resources.design-tips'
import { Route as ResourcesDesignForMachiningToolkitRouteImport } from './routes/resources.design-for-machining-toolkit'
import { Route as MaterialsToolSteelRouteImport } from './routes/materials.tool-steel'
import { Route as MaterialsTitaniumRouteImport } from './routes/materials.titanium'
import { Route as MaterialsStainlessSteelRouteImport } from './routes/materials.stainless-steel'
import { Route as MaterialsPolycarbonateRouteImport } from './routes/materials.polycarbonate'
import { Route as MaterialsPeekRouteImport } from './routes/materials.peek'
import { Route as MaterialsNylonRouteImport } from './routes/materials.nylon'
import { Route as MaterialsMildSteelRouteImport } from './routes/materials.mild-steel'
import { Route as MaterialsDieCastingRouteImport } from './routes/materials.die-casting'
import { Route as MaterialsDelrinRouteImport } from './routes/materials.delrin'
import { Route as MaterialsCopperRouteImport } from './routes/materials.copper'
import { Route as MaterialsBronzeRouteImport } from './routes/materials.bronze'
import { Route as MaterialsBrassRouteImport } from './routes/materials.brass'
import { Route as MaterialsAluminumRouteImport } from './routes/materials.aluminum'
import { Route as MaterialsAbsRouteImport } from './routes/materials.abs'
import { Route as IndustriesRoboticsRouteImport } from './routes/industries.robotics'
import { Route as IndustriesOilAndGasRouteImport } from './routes/industries.oil-and-gas'
import { Route as IndustriesMedicalRouteImport } from './routes/industries.medical'
import { Route as IndustriesIndustrialEquipmentRouteImport } from './routes/industries.industrial-equipment'
import { Route as IndustriesEnergyRouteImport } from './routes/industries.energy'
import { Route as IndustriesElectronicsRouteImport } from './routes/industries.electronics'
import { Route as IndustriesDefenceRouteImport } from './routes/industries.defence'
import { Route as IndustriesConsumerElectronicsRouteImport } from './routes/industries.consumer-electronics'
import { Route as IndustriesAutomotiveRouteImport } from './routes/industries.automotive'
import { Route as IndustriesAerospaceRouteImport } from './routes/industries.aerospace'
import { Route as ServicesDieCastingQualityRouteImport } from './routes/services.die-casting.quality'
import { Route as ServicesCncMachiningCncTurningRouteImport } from './routes/services.cnc-machining.cnc-turning'
import { Route as ServicesCncMachiningCncMillingRouteImport } from './routes/services.cnc-machining.cnc-milling'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypingToProductionRoute = PrototypingToProductionRouteImport.update({
  id: '/prototyping-to-production',
  path: '/prototyping-to-production',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FactoryRoute = FactoryRouteImport.update({
  id: '/factory',
  path: '/factory',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRoute,
} as any)
const MaterialsIndexRoute = MaterialsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MaterialsRoute,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndustriesRoute,
} as any)
const ServicesWireEdmRoute = ServicesWireEdmRouteImport.update({
  id: '/wire-edm',
  path: '/wire-edm',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesToolAndDieRoute = ServicesToolAndDieRouteImport.update({
  id: '/tool-and-die',
  path: '/tool-and-die',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSurfaceGrindingRoute = ServicesSurfaceGrindingRouteImport.update({
  id: '/surface-grinding',
  path: '/surface-grinding',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesReverseEngineeringRoute =
  ServicesReverseEngineeringRouteImport.update({
    id: '/reverse-engineering',
    path: '/reverse-engineering',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesRapidPrototypingRoute =
  ServicesRapidPrototypingRouteImport.update({
    id: '/rapid-prototyping',
    path: '/rapid-prototyping',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesProductionRoute = ServicesProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesProductDevelopmentRoute =
  ServicesProductDevelopmentRouteImport.update({
    id: '/product-development',
    path: '/product-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesPrecisionComponentsRoute =
  ServicesPrecisionComponentsRouteImport.update({
    id: '/precision-components',
    path: '/precision-components',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesPlasticInjectionMoldingRoute =
  ServicesPlasticInjectionMoldingRouteImport.update({
    id: '/plastic-injection-molding',
    path: '/plastic-injection-molding',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesLedLightsRoute = ServicesLedLightsRouteImport.update({
  id: '/led-lights',
  path: '/led-lights',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesInjectionMoldManufacturingRoute =
  ServicesInjectionMoldManufacturingRouteImport.update({
    id: '/injection-mold-manufacturing',
    path: '/injection-mold-manufacturing',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesDieCastingRoute = ServicesDieCastingRouteImport.update({
  id: '/die-casting',
  path: '/die-casting',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCustomManufacturingRoute =
  ServicesCustomManufacturingRouteImport.update({
    id: '/custom-manufacturing',
    path: '/custom-manufacturing',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesCncMachiningRoute = ServicesCncMachiningRouteImport.update({
  id: '/cnc-machining',
  path: '/cnc-machining',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCadCamDesignRoute = ServicesCadCamDesignRouteImport.update({
  id: '/cad-cam-design',
  path: '/cad-cam-design',
  getParentRoute: () => ServicesRoute,
} as any)
const Services3dScanningRoute = Services3dScanningRouteImport.update({
  id: '/3d-scanning',
  path: '/3d-scanning',
  getParentRoute: () => ServicesRoute,
} as any)
const ResourcesProductLifeCycleRoute =
  ResourcesProductLifeCycleRouteImport.update({
    id: '/product-life-cycle',
    path: '/product-life-cycle',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ResourcesDesignTipsRoute = ResourcesDesignTipsRouteImport.update({
  id: '/design-tips',
  path: '/design-tips',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesDesignForMachiningToolkitRoute =
  ResourcesDesignForMachiningToolkitRouteImport.update({
    id: '/design-for-machining-toolkit',
    path: '/design-for-machining-toolkit',
    getParentRoute: () => ResourcesRoute,
  } as any)
const MaterialsToolSteelRoute = MaterialsToolSteelRouteImport.update({
  id: '/tool-steel',
  path: '/tool-steel',
  getParentRoute: () => MaterialsRoute,
} as any)
const MaterialsTitaniumRoute = MaterialsTitaniumRouteImport.update({
  id: '/titanium',
  path: '/titanium',
  getParentRoute: () => MaterialsRoute,
} as any)
const MaterialsStainlessSteelRoute = MaterialsStainlessSteelRouteImport.update({
  id: '/stainless-steel',
  path: '/stainless-steel',
  getParentRoute: () => MaterialsRoute,
} as any)
const MaterialsPolycarbonateRoute = MaterialsPolycarbonateRouteImport.update({
  id: '/polycarbonate',
  path: '/polycarbonate',
  getParentRoute: () => MaterialsRoute,
} as any)
const MaterialsPeekRoute = MaterialsPeekRouteImport.update({
  id: '/peek',
  path: '/peek',
  getParentRoute: () => MaterialsRoute,
} as any)
const MaterialsNylonRoute = MaterialsNylonRouteImport.update({
  id: '/nylon',
  path: '/nylon',
  getParentRoute: () => MaterialsRoute,
} as any)
const MaterialsMildSteelRoute = MaterialsMildSteelRouteImport.update({
  id: '/mild-steel',
  path: '/mild-steel',
  getParentRoute: () => MaterialsRoute,
} as any)
const MaterialsDieCastingRoute = MaterialsDieCastingRouteImport.update({
  id: '/die-casting',
  path: '/die-casting',
  getParentRoute: () => MaterialsRoute,
} as any)
const MaterialsDelrinRoute = MaterialsDelrinRouteImport.update({
  id: '/delrin',
  path: '/delrin',
  getParentRoute: () => MaterialsRoute,
} as any)
const MaterialsCopperRoute = MaterialsCopperRouteImport.update({
  id: '/copper',
  path: '/copper',
  getParentRoute: () => MaterialsRoute,
} as any)
const MaterialsBronzeRoute = MaterialsBronzeRouteImport.update({
  id: '/bronze',
  path: '/bronze',
  getParentRoute: () => MaterialsRoute,
} as any)
const MaterialsBrassRoute = MaterialsBrassRouteImport.update({
  id: '/brass',
  path: '/brass',
  getParentRoute: () => MaterialsRoute,
} as any)
const MaterialsAluminumRoute = MaterialsAluminumRouteImport.update({
  id: '/aluminum',
  path: '/aluminum',
  getParentRoute: () => MaterialsRoute,
} as any)
const MaterialsAbsRoute = MaterialsAbsRouteImport.update({
  id: '/abs',
  path: '/abs',
  getParentRoute: () => MaterialsRoute,
} as any)
const IndustriesRoboticsRoute = IndustriesRoboticsRouteImport.update({
  id: '/robotics',
  path: '/robotics',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesOilAndGasRoute = IndustriesOilAndGasRouteImport.update({
  id: '/oil-and-gas',
  path: '/oil-and-gas',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesMedicalRoute = IndustriesMedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesIndustrialEquipmentRoute =
  IndustriesIndustrialEquipmentRouteImport.update({
    id: '/industrial-equipment',
    path: '/industrial-equipment',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesEnergyRoute = IndustriesEnergyRouteImport.update({
  id: '/energy',
  path: '/energy',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesElectronicsRoute = IndustriesElectronicsRouteImport.update({
  id: '/electronics',
  path: '/electronics',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesDefenceRoute = IndustriesDefenceRouteImport.update({
  id: '/defence',
  path: '/defence',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesConsumerElectronicsRoute =
  IndustriesConsumerElectronicsRouteImport.update({
    id: '/consumer-electronics',
    path: '/consumer-electronics',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesAutomotiveRoute = IndustriesAutomotiveRouteImport.update({
  id: '/automotive',
  path: '/automotive',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesAerospaceRoute = IndustriesAerospaceRouteImport.update({
  id: '/aerospace',
  path: '/aerospace',
  getParentRoute: () => IndustriesRoute,
} as any)
const ServicesDieCastingQualityRoute =
  ServicesDieCastingQualityRouteImport.update({
    id: '/quality',
    path: '/quality',
    getParentRoute: () => ServicesDieCastingRoute,
  } as any)
const ServicesCncMachiningCncTurningRoute =
  ServicesCncMachiningCncTurningRouteImport.update({
    id: '/cnc-turning',
    path: '/cnc-turning',
    getParentRoute: () => ServicesCncMachiningRoute,
  } as any)
const ServicesCncMachiningCncMillingRoute =
  ServicesCncMachiningCncMillingRouteImport.update({
    id: '/cnc-milling',
    path: '/cnc-milling',
    getParentRoute: () => ServicesCncMachiningRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/capabilities': typeof CapabilitiesRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/equipment': typeof EquipmentRoute
  '/factory': typeof FactoryRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/materials': typeof MaterialsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/prototyping-to-production': typeof PrototypingToProductionRoute
  '/quality': typeof QualityRoute
  '/quote': typeof QuoteRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/industries/aerospace': typeof IndustriesAerospaceRoute
  '/industries/automotive': typeof IndustriesAutomotiveRoute
  '/industries/consumer-electronics': typeof IndustriesConsumerElectronicsRoute
  '/industries/defence': typeof IndustriesDefenceRoute
  '/industries/electronics': typeof IndustriesElectronicsRoute
  '/industries/energy': typeof IndustriesEnergyRoute
  '/industries/industrial-equipment': typeof IndustriesIndustrialEquipmentRoute
  '/industries/medical': typeof IndustriesMedicalRoute
  '/industries/oil-and-gas': typeof IndustriesOilAndGasRoute
  '/industries/robotics': typeof IndustriesRoboticsRoute
  '/materials/abs': typeof MaterialsAbsRoute
  '/materials/aluminum': typeof MaterialsAluminumRoute
  '/materials/brass': typeof MaterialsBrassRoute
  '/materials/bronze': typeof MaterialsBronzeRoute
  '/materials/copper': typeof MaterialsCopperRoute
  '/materials/delrin': typeof MaterialsDelrinRoute
  '/materials/die-casting': typeof MaterialsDieCastingRoute
  '/materials/mild-steel': typeof MaterialsMildSteelRoute
  '/materials/nylon': typeof MaterialsNylonRoute
  '/materials/peek': typeof MaterialsPeekRoute
  '/materials/polycarbonate': typeof MaterialsPolycarbonateRoute
  '/materials/stainless-steel': typeof MaterialsStainlessSteelRoute
  '/materials/titanium': typeof MaterialsTitaniumRoute
  '/materials/tool-steel': typeof MaterialsToolSteelRoute
  '/resources/design-for-machining-toolkit': typeof ResourcesDesignForMachiningToolkitRoute
  '/resources/design-tips': typeof ResourcesDesignTipsRoute
  '/resources/product-life-cycle': typeof ResourcesProductLifeCycleRoute
  '/services/3d-scanning': typeof Services3dScanningRoute
  '/services/cad-cam-design': typeof ServicesCadCamDesignRoute
  '/services/cnc-machining': typeof ServicesCncMachiningRouteWithChildren
  '/services/custom-manufacturing': typeof ServicesCustomManufacturingRoute
  '/services/die-casting': typeof ServicesDieCastingRouteWithChildren
  '/services/injection-mold-manufacturing': typeof ServicesInjectionMoldManufacturingRoute
  '/services/led-lights': typeof ServicesLedLightsRoute
  '/services/plastic-injection-molding': typeof ServicesPlasticInjectionMoldingRoute
  '/services/precision-components': typeof ServicesPrecisionComponentsRoute
  '/services/product-development': typeof ServicesProductDevelopmentRoute
  '/services/production': typeof ServicesProductionRoute
  '/services/rapid-prototyping': typeof ServicesRapidPrototypingRoute
  '/services/reverse-engineering': typeof ServicesReverseEngineeringRoute
  '/services/surface-grinding': typeof ServicesSurfaceGrindingRoute
  '/services/tool-and-die': typeof ServicesToolAndDieRoute
  '/services/wire-edm': typeof ServicesWireEdmRoute
  '/industries/': typeof IndustriesIndexRoute
  '/materials/': typeof MaterialsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/cnc-machining/cnc-milling': typeof ServicesCncMachiningCncMillingRoute
  '/services/cnc-machining/cnc-turning': typeof ServicesCncMachiningCncTurningRoute
  '/services/die-casting/quality': typeof ServicesDieCastingQualityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/capabilities': typeof CapabilitiesRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/equipment': typeof EquipmentRoute
  '/factory': typeof FactoryRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/prototyping-to-production': typeof PrototypingToProductionRoute
  '/quality': typeof QualityRoute
  '/quote': typeof QuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/industries/aerospace': typeof IndustriesAerospaceRoute
  '/industries/automotive': typeof IndustriesAutomotiveRoute
  '/industries/consumer-electronics': typeof IndustriesConsumerElectronicsRoute
  '/industries/defence': typeof IndustriesDefenceRoute
  '/industries/electronics': typeof IndustriesElectronicsRoute
  '/industries/energy': typeof IndustriesEnergyRoute
  '/industries/industrial-equipment': typeof IndustriesIndustrialEquipmentRoute
  '/industries/medical': typeof IndustriesMedicalRoute
  '/industries/oil-and-gas': typeof IndustriesOilAndGasRoute
  '/industries/robotics': typeof IndustriesRoboticsRoute
  '/materials/abs': typeof MaterialsAbsRoute
  '/materials/aluminum': typeof MaterialsAluminumRoute
  '/materials/brass': typeof MaterialsBrassRoute
  '/materials/bronze': typeof MaterialsBronzeRoute
  '/materials/copper': typeof MaterialsCopperRoute
  '/materials/delrin': typeof MaterialsDelrinRoute
  '/materials/die-casting': typeof MaterialsDieCastingRoute
  '/materials/mild-steel': typeof MaterialsMildSteelRoute
  '/materials/nylon': typeof MaterialsNylonRoute
  '/materials/peek': typeof MaterialsPeekRoute
  '/materials/polycarbonate': typeof MaterialsPolycarbonateRoute
  '/materials/stainless-steel': typeof MaterialsStainlessSteelRoute
  '/materials/titanium': typeof MaterialsTitaniumRoute
  '/materials/tool-steel': typeof MaterialsToolSteelRoute
  '/resources/design-for-machining-toolkit': typeof ResourcesDesignForMachiningToolkitRoute
  '/resources/design-tips': typeof ResourcesDesignTipsRoute
  '/resources/product-life-cycle': typeof ResourcesProductLifeCycleRoute
  '/services/3d-scanning': typeof Services3dScanningRoute
  '/services/cad-cam-design': typeof ServicesCadCamDesignRoute
  '/services/cnc-machining': typeof ServicesCncMachiningRouteWithChildren
  '/services/custom-manufacturing': typeof ServicesCustomManufacturingRoute
  '/services/die-casting': typeof ServicesDieCastingRouteWithChildren
  '/services/injection-mold-manufacturing': typeof ServicesInjectionMoldManufacturingRoute
  '/services/led-lights': typeof ServicesLedLightsRoute
  '/services/plastic-injection-molding': typeof ServicesPlasticInjectionMoldingRoute
  '/services/precision-components': typeof ServicesPrecisionComponentsRoute
  '/services/product-development': typeof ServicesProductDevelopmentRoute
  '/services/production': typeof ServicesProductionRoute
  '/services/rapid-prototyping': typeof ServicesRapidPrototypingRoute
  '/services/reverse-engineering': typeof ServicesReverseEngineeringRoute
  '/services/surface-grinding': typeof ServicesSurfaceGrindingRoute
  '/services/tool-and-die': typeof ServicesToolAndDieRoute
  '/services/wire-edm': typeof ServicesWireEdmRoute
  '/industries': typeof IndustriesIndexRoute
  '/materials': typeof MaterialsIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/services': typeof ServicesIndexRoute
  '/services/cnc-machining/cnc-milling': typeof ServicesCncMachiningCncMillingRoute
  '/services/cnc-machining/cnc-turning': typeof ServicesCncMachiningCncTurningRoute
  '/services/die-casting/quality': typeof ServicesDieCastingQualityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/capabilities': typeof CapabilitiesRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/equipment': typeof EquipmentRoute
  '/factory': typeof FactoryRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/materials': typeof MaterialsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/prototyping-to-production': typeof PrototypingToProductionRoute
  '/quality': typeof QualityRoute
  '/quote': typeof QuoteRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/industries/aerospace': typeof IndustriesAerospaceRoute
  '/industries/automotive': typeof IndustriesAutomotiveRoute
  '/industries/consumer-electronics': typeof IndustriesConsumerElectronicsRoute
  '/industries/defence': typeof IndustriesDefenceRoute
  '/industries/electronics': typeof IndustriesElectronicsRoute
  '/industries/energy': typeof IndustriesEnergyRoute
  '/industries/industrial-equipment': typeof IndustriesIndustrialEquipmentRoute
  '/industries/medical': typeof IndustriesMedicalRoute
  '/industries/oil-and-gas': typeof IndustriesOilAndGasRoute
  '/industries/robotics': typeof IndustriesRoboticsRoute
  '/materials/abs': typeof MaterialsAbsRoute
  '/materials/aluminum': typeof MaterialsAluminumRoute
  '/materials/brass': typeof MaterialsBrassRoute
  '/materials/bronze': typeof MaterialsBronzeRoute
  '/materials/copper': typeof MaterialsCopperRoute
  '/materials/delrin': typeof MaterialsDelrinRoute
  '/materials/die-casting': typeof MaterialsDieCastingRoute
  '/materials/mild-steel': typeof MaterialsMildSteelRoute
  '/materials/nylon': typeof MaterialsNylonRoute
  '/materials/peek': typeof MaterialsPeekRoute
  '/materials/polycarbonate': typeof MaterialsPolycarbonateRoute
  '/materials/stainless-steel': typeof MaterialsStainlessSteelRoute
  '/materials/titanium': typeof MaterialsTitaniumRoute
  '/materials/tool-steel': typeof MaterialsToolSteelRoute
  '/resources/design-for-machining-toolkit': typeof ResourcesDesignForMachiningToolkitRoute
  '/resources/design-tips': typeof ResourcesDesignTipsRoute
  '/resources/product-life-cycle': typeof ResourcesProductLifeCycleRoute
  '/services/3d-scanning': typeof Services3dScanningRoute
  '/services/cad-cam-design': typeof ServicesCadCamDesignRoute
  '/services/cnc-machining': typeof ServicesCncMachiningRouteWithChildren
  '/services/custom-manufacturing': typeof ServicesCustomManufacturingRoute
  '/services/die-casting': typeof ServicesDieCastingRouteWithChildren
  '/services/injection-mold-manufacturing': typeof ServicesInjectionMoldManufacturingRoute
  '/services/led-lights': typeof ServicesLedLightsRoute
  '/services/plastic-injection-molding': typeof ServicesPlasticInjectionMoldingRoute
  '/services/precision-components': typeof ServicesPrecisionComponentsRoute
  '/services/product-development': typeof ServicesProductDevelopmentRoute
  '/services/production': typeof ServicesProductionRoute
  '/services/rapid-prototyping': typeof ServicesRapidPrototypingRoute
  '/services/reverse-engineering': typeof ServicesReverseEngineeringRoute
  '/services/surface-grinding': typeof ServicesSurfaceGrindingRoute
  '/services/tool-and-die': typeof ServicesToolAndDieRoute
  '/services/wire-edm': typeof ServicesWireEdmRoute
  '/industries/': typeof IndustriesIndexRoute
  '/materials/': typeof MaterialsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/cnc-machining/cnc-milling': typeof ServicesCncMachiningCncMillingRoute
  '/services/cnc-machining/cnc-turning': typeof ServicesCncMachiningCncTurningRoute
  '/services/die-casting/quality': typeof ServicesDieCastingQualityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/capabilities'
    | '/careers'
    | '/case-studies'
    | '/certifications'
    | '/contact'
    | '/downloads'
    | '/equipment'
    | '/factory'
    | '/faq'
    | '/gallery'
    | '/industries'
    | '/materials'
    | '/privacy'
    | '/projects'
    | '/prototyping-to-production'
    | '/quality'
    | '/quote'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/industries/aerospace'
    | '/industries/automotive'
    | '/industries/consumer-electronics'
    | '/industries/defence'
    | '/industries/electronics'
    | '/industries/energy'
    | '/industries/industrial-equipment'
    | '/industries/medical'
    | '/industries/oil-and-gas'
    | '/industries/robotics'
    | '/materials/abs'
    | '/materials/aluminum'
    | '/materials/brass'
    | '/materials/bronze'
    | '/materials/copper'
    | '/materials/delrin'
    | '/materials/die-casting'
    | '/materials/mild-steel'
    | '/materials/nylon'
    | '/materials/peek'
    | '/materials/polycarbonate'
    | '/materials/stainless-steel'
    | '/materials/titanium'
    | '/materials/tool-steel'
    | '/resources/design-for-machining-toolkit'
    | '/resources/design-tips'
    | '/resources/product-life-cycle'
    | '/services/3d-scanning'
    | '/services/cad-cam-design'
    | '/services/cnc-machining'
    | '/services/custom-manufacturing'
    | '/services/die-casting'
    | '/services/injection-mold-manufacturing'
    | '/services/led-lights'
    | '/services/plastic-injection-molding'
    | '/services/precision-components'
    | '/services/product-development'
    | '/services/production'
    | '/services/rapid-prototyping'
    | '/services/reverse-engineering'
    | '/services/surface-grinding'
    | '/services/tool-and-die'
    | '/services/wire-edm'
    | '/industries/'
    | '/materials/'
    | '/resources/'
    | '/services/'
    | '/services/cnc-machining/cnc-milling'
    | '/services/cnc-machining/cnc-turning'
    | '/services/die-casting/quality'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/capabilities'
    | '/careers'
    | '/case-studies'
    | '/certifications'
    | '/contact'
    | '/downloads'
    | '/equipment'
    | '/factory'
    | '/faq'
    | '/gallery'
    | '/privacy'
    | '/projects'
    | '/prototyping-to-production'
    | '/quality'
    | '/quote'
    | '/sitemap.xml'
    | '/industries/aerospace'
    | '/industries/automotive'
    | '/industries/consumer-electronics'
    | '/industries/defence'
    | '/industries/electronics'
    | '/industries/energy'
    | '/industries/industrial-equipment'
    | '/industries/medical'
    | '/industries/oil-and-gas'
    | '/industries/robotics'
    | '/materials/abs'
    | '/materials/aluminum'
    | '/materials/brass'
    | '/materials/bronze'
    | '/materials/copper'
    | '/materials/delrin'
    | '/materials/die-casting'
    | '/materials/mild-steel'
    | '/materials/nylon'
    | '/materials/peek'
    | '/materials/polycarbonate'
    | '/materials/stainless-steel'
    | '/materials/titanium'
    | '/materials/tool-steel'
    | '/resources/design-for-machining-toolkit'
    | '/resources/design-tips'
    | '/resources/product-life-cycle'
    | '/services/3d-scanning'
    | '/services/cad-cam-design'
    | '/services/cnc-machining'
    | '/services/custom-manufacturing'
    | '/services/die-casting'
    | '/services/injection-mold-manufacturing'
    | '/services/led-lights'
    | '/services/plastic-injection-molding'
    | '/services/precision-components'
    | '/services/product-development'
    | '/services/production'
    | '/services/rapid-prototyping'
    | '/services/reverse-engineering'
    | '/services/surface-grinding'
    | '/services/tool-and-die'
    | '/services/wire-edm'
    | '/industries'
    | '/materials'
    | '/resources'
    | '/services'
    | '/services/cnc-machining/cnc-milling'
    | '/services/cnc-machining/cnc-turning'
    | '/services/die-casting/quality'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/capabilities'
    | '/careers'
    | '/case-studies'
    | '/certifications'
    | '/contact'
    | '/downloads'
    | '/equipment'
    | '/factory'
    | '/faq'
    | '/gallery'
    | '/industries'
    | '/materials'
    | '/privacy'
    | '/projects'
    | '/prototyping-to-production'
    | '/quality'
    | '/quote'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/industries/aerospace'
    | '/industries/automotive'
    | '/industries/consumer-electronics'
    | '/industries/defence'
    | '/industries/electronics'
    | '/industries/energy'
    | '/industries/industrial-equipment'
    | '/industries/medical'
    | '/industries/oil-and-gas'
    | '/industries/robotics'
    | '/materials/abs'
    | '/materials/aluminum'
    | '/materials/brass'
    | '/materials/bronze'
    | '/materials/copper'
    | '/materials/delrin'
    | '/materials/die-casting'
    | '/materials/mild-steel'
    | '/materials/nylon'
    | '/materials/peek'
    | '/materials/polycarbonate'
    | '/materials/stainless-steel'
    | '/materials/titanium'
    | '/materials/tool-steel'
    | '/resources/design-for-machining-toolkit'
    | '/resources/design-tips'
    | '/resources/product-life-cycle'
    | '/services/3d-scanning'
    | '/services/cad-cam-design'
    | '/services/cnc-machining'
    | '/services/custom-manufacturing'
    | '/services/die-casting'
    | '/services/injection-mold-manufacturing'
    | '/services/led-lights'
    | '/services/plastic-injection-molding'
    | '/services/precision-components'
    | '/services/product-development'
    | '/services/production'
    | '/services/rapid-prototyping'
    | '/services/reverse-engineering'
    | '/services/surface-grinding'
    | '/services/tool-and-die'
    | '/services/wire-edm'
    | '/industries/'
    | '/materials/'
    | '/resources/'
    | '/services/'
    | '/services/cnc-machining/cnc-milling'
    | '/services/cnc-machining/cnc-turning'
    | '/services/die-casting/quality'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CapabilitiesRoute: typeof CapabilitiesRoute
  CareersRoute: typeof CareersRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  CertificationsRoute: typeof CertificationsRoute
  ContactRoute: typeof ContactRoute
  DownloadsRoute: typeof DownloadsRoute
  EquipmentRoute: typeof EquipmentRoute
  FactoryRoute: typeof FactoryRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  MaterialsRoute: typeof MaterialsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRoute
  PrototypingToProductionRoute: typeof PrototypingToProductionRoute
  QualityRoute: typeof QualityRoute
  QuoteRoute: typeof QuoteRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototyping-to-production': {
      id: '/prototyping-to-production'
      path: '/prototyping-to-production'
      fullPath: '/prototyping-to-production'
      preLoaderRoute: typeof PrototypingToProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factory': {
      id: '/factory'
      path: '/factory'
      fullPath: '/factory'
      preLoaderRoute: typeof FactoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/materials/': {
      id: '/materials/'
      path: '/'
      fullPath: '/materials/'
      preLoaderRoute: typeof MaterialsIndexRouteImport
      parentRoute: typeof MaterialsRoute
    }
    '/industries/': {
      id: '/industries/'
      path: '/'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/services/wire-edm': {
      id: '/services/wire-edm'
      path: '/wire-edm'
      fullPath: '/services/wire-edm'
      preLoaderRoute: typeof ServicesWireEdmRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/tool-and-die': {
      id: '/services/tool-and-die'
      path: '/tool-and-die'
      fullPath: '/services/tool-and-die'
      preLoaderRoute: typeof ServicesToolAndDieRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/surface-grinding': {
      id: '/services/surface-grinding'
      path: '/surface-grinding'
      fullPath: '/services/surface-grinding'
      preLoaderRoute: typeof ServicesSurfaceGrindingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/reverse-engineering': {
      id: '/services/reverse-engineering'
      path: '/reverse-engineering'
      fullPath: '/services/reverse-engineering'
      preLoaderRoute: typeof ServicesReverseEngineeringRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/rapid-prototyping': {
      id: '/services/rapid-prototyping'
      path: '/rapid-prototyping'
      fullPath: '/services/rapid-prototyping'
      preLoaderRoute: typeof ServicesRapidPrototypingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/production': {
      id: '/services/production'
      path: '/production'
      fullPath: '/services/production'
      preLoaderRoute: typeof ServicesProductionRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/product-development': {
      id: '/services/product-development'
      path: '/product-development'
      fullPath: '/services/product-development'
      preLoaderRoute: typeof ServicesProductDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/precision-components': {
      id: '/services/precision-components'
      path: '/precision-components'
      fullPath: '/services/precision-components'
      preLoaderRoute: typeof ServicesPrecisionComponentsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/plastic-injection-molding': {
      id: '/services/plastic-injection-molding'
      path: '/plastic-injection-molding'
      fullPath: '/services/plastic-injection-molding'
      preLoaderRoute: typeof ServicesPlasticInjectionMoldingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/led-lights': {
      id: '/services/led-lights'
      path: '/led-lights'
      fullPath: '/services/led-lights'
      preLoaderRoute: typeof ServicesLedLightsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/injection-mold-manufacturing': {
      id: '/services/injection-mold-manufacturing'
      path: '/injection-mold-manufacturing'
      fullPath: '/services/injection-mold-manufacturing'
      preLoaderRoute: typeof ServicesInjectionMoldManufacturingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/die-casting': {
      id: '/services/die-casting'
      path: '/die-casting'
      fullPath: '/services/die-casting'
      preLoaderRoute: typeof ServicesDieCastingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/custom-manufacturing': {
      id: '/services/custom-manufacturing'
      path: '/custom-manufacturing'
      fullPath: '/services/custom-manufacturing'
      preLoaderRoute: typeof ServicesCustomManufacturingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cnc-machining': {
      id: '/services/cnc-machining'
      path: '/cnc-machining'
      fullPath: '/services/cnc-machining'
      preLoaderRoute: typeof ServicesCncMachiningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cad-cam-design': {
      id: '/services/cad-cam-design'
      path: '/cad-cam-design'
      fullPath: '/services/cad-cam-design'
      preLoaderRoute: typeof ServicesCadCamDesignRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/3d-scanning': {
      id: '/services/3d-scanning'
      path: '/3d-scanning'
      fullPath: '/services/3d-scanning'
      preLoaderRoute: typeof Services3dScanningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/resources/product-life-cycle': {
      id: '/resources/product-life-cycle'
      path: '/product-life-cycle'
      fullPath: '/resources/product-life-cycle'
      preLoaderRoute: typeof ResourcesProductLifeCycleRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/design-tips': {
      id: '/resources/design-tips'
      path: '/design-tips'
      fullPath: '/resources/design-tips'
      preLoaderRoute: typeof ResourcesDesignTipsRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/design-for-machining-toolkit': {
      id: '/resources/design-for-machining-toolkit'
      path: '/design-for-machining-toolkit'
      fullPath: '/resources/design-for-machining-toolkit'
      preLoaderRoute: typeof ResourcesDesignForMachiningToolkitRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/materials/tool-steel': {
      id: '/materials/tool-steel'
      path: '/tool-steel'
      fullPath: '/materials/tool-steel'
      preLoaderRoute: typeof MaterialsToolSteelRouteImport
      parentRoute: typeof MaterialsRoute
    }
    '/materials/titanium': {
      id: '/materials/titanium'
      path: '/titanium'
      fullPath: '/materials/titanium'
      preLoaderRoute: typeof MaterialsTitaniumRouteImport
      parentRoute: typeof MaterialsRoute
    }
    '/materials/stainless-steel': {
      id: '/materials/stainless-steel'
      path: '/stainless-steel'
      fullPath: '/materials/stainless-steel'
      preLoaderRoute: typeof MaterialsStainlessSteelRouteImport
      parentRoute: typeof MaterialsRoute
    }
    '/materials/polycarbonate': {
      id: '/materials/polycarbonate'
      path: '/polycarbonate'
      fullPath: '/materials/polycarbonate'
      preLoaderRoute: typeof MaterialsPolycarbonateRouteImport
      parentRoute: typeof MaterialsRoute
    }
    '/materials/peek': {
      id: '/materials/peek'
      path: '/peek'
      fullPath: '/materials/peek'
      preLoaderRoute: typeof MaterialsPeekRouteImport
      parentRoute: typeof MaterialsRoute
    }
    '/materials/nylon': {
      id: '/materials/nylon'
      path: '/nylon'
      fullPath: '/materials/nylon'
      preLoaderRoute: typeof MaterialsNylonRouteImport
      parentRoute: typeof MaterialsRoute
    }
    '/materials/mild-steel': {
      id: '/materials/mild-steel'
      path: '/mild-steel'
      fullPath: '/materials/mild-steel'
      preLoaderRoute: typeof MaterialsMildSteelRouteImport
      parentRoute: typeof MaterialsRoute
    }
    '/materials/die-casting': {
      id: '/materials/die-casting'
      path: '/die-casting'
      fullPath: '/materials/die-casting'
      preLoaderRoute: typeof MaterialsDieCastingRouteImport
      parentRoute: typeof MaterialsRoute
    }
    '/materials/delrin': {
      id: '/materials/delrin'
      path: '/delrin'
      fullPath: '/materials/delrin'
      preLoaderRoute: typeof MaterialsDelrinRouteImport
      parentRoute: typeof MaterialsRoute
    }
    '/materials/copper': {
      id: '/materials/copper'
      path: '/copper'
      fullPath: '/materials/copper'
      preLoaderRoute: typeof MaterialsCopperRouteImport
      parentRoute: typeof MaterialsRoute
    }
    '/materials/bronze': {
      id: '/materials/bronze'
      path: '/bronze'
      fullPath: '/materials/bronze'
      preLoaderRoute: typeof MaterialsBronzeRouteImport
      parentRoute: typeof MaterialsRoute
    }
    '/materials/brass': {
      id: '/materials/brass'
      path: '/brass'
      fullPath: '/materials/brass'
      preLoaderRoute: typeof MaterialsBrassRouteImport
      parentRoute: typeof MaterialsRoute
    }
    '/materials/aluminum': {
      id: '/materials/aluminum'
      path: '/aluminum'
      fullPath: '/materials/aluminum'
      preLoaderRoute: typeof MaterialsAluminumRouteImport
      parentRoute: typeof MaterialsRoute
    }
    '/materials/abs': {
      id: '/materials/abs'
      path: '/abs'
      fullPath: '/materials/abs'
      preLoaderRoute: typeof MaterialsAbsRouteImport
      parentRoute: typeof MaterialsRoute
    }
    '/industries/robotics': {
      id: '/industries/robotics'
      path: '/robotics'
      fullPath: '/industries/robotics'
      preLoaderRoute: typeof IndustriesRoboticsRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/oil-and-gas': {
      id: '/industries/oil-and-gas'
      path: '/oil-and-gas'
      fullPath: '/industries/oil-and-gas'
      preLoaderRoute: typeof IndustriesOilAndGasRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/medical': {
      id: '/industries/medical'
      path: '/medical'
      fullPath: '/industries/medical'
      preLoaderRoute: typeof IndustriesMedicalRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/industrial-equipment': {
      id: '/industries/industrial-equipment'
      path: '/industrial-equipment'
      fullPath: '/industries/industrial-equipment'
      preLoaderRoute: typeof IndustriesIndustrialEquipmentRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/energy': {
      id: '/industries/energy'
      path: '/energy'
      fullPath: '/industries/energy'
      preLoaderRoute: typeof IndustriesEnergyRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/electronics': {
      id: '/industries/electronics'
      path: '/electronics'
      fullPath: '/industries/electronics'
      preLoaderRoute: typeof IndustriesElectronicsRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/defence': {
      id: '/industries/defence'
      path: '/defence'
      fullPath: '/industries/defence'
      preLoaderRoute: typeof IndustriesDefenceRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/consumer-electronics': {
      id: '/industries/consumer-electronics'
      path: '/consumer-electronics'
      fullPath: '/industries/consumer-electronics'
      preLoaderRoute: typeof IndustriesConsumerElectronicsRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/automotive': {
      id: '/industries/automotive'
      path: '/automotive'
      fullPath: '/industries/automotive'
      preLoaderRoute: typeof IndustriesAutomotiveRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/aerospace': {
      id: '/industries/aerospace'
      path: '/aerospace'
      fullPath: '/industries/aerospace'
      preLoaderRoute: typeof IndustriesAerospaceRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/services/die-casting/quality': {
      id: '/services/die-casting/quality'
      path: '/quality'
      fullPath: '/services/die-casting/quality'
      preLoaderRoute: typeof ServicesDieCastingQualityRouteImport
      parentRoute: typeof ServicesDieCastingRoute
    }
    '/services/cnc-machining/cnc-turning': {
      id: '/services/cnc-machining/cnc-turning'
      path: '/cnc-turning'
      fullPath: '/services/cnc-machining/cnc-turning'
      preLoaderRoute: typeof ServicesCncMachiningCncTurningRouteImport
      parentRoute: typeof ServicesCncMachiningRoute
    }
    '/services/cnc-machining/cnc-milling': {
      id: '/services/cnc-machining/cnc-milling'
      path: '/cnc-milling'
      fullPath: '/services/cnc-machining/cnc-milling'
      preLoaderRoute: typeof ServicesCncMachiningCncMillingRouteImport
      parentRoute: typeof ServicesCncMachiningRoute
    }
  }
}

interface IndustriesRouteChildren {
  IndustriesAerospaceRoute: typeof IndustriesAerospaceRoute
  IndustriesAutomotiveRoute: typeof IndustriesAutomotiveRoute
  IndustriesConsumerElectronicsRoute: typeof IndustriesConsumerElectronicsRoute
  IndustriesDefenceRoute: typeof IndustriesDefenceRoute
  IndustriesElectronicsRoute: typeof IndustriesElectronicsRoute
  IndustriesEnergyRoute: typeof IndustriesEnergyRoute
  IndustriesIndustrialEquipmentRoute: typeof IndustriesIndustrialEquipmentRoute
  IndustriesMedicalRoute: typeof IndustriesMedicalRoute
  IndustriesOilAndGasRoute: typeof IndustriesOilAndGasRoute
  IndustriesRoboticsRoute: typeof IndustriesRoboticsRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesAerospaceRoute: IndustriesAerospaceRoute,
  IndustriesAutomotiveRoute: IndustriesAutomotiveRoute,
  IndustriesConsumerElectronicsRoute: IndustriesConsumerElectronicsRoute,
  IndustriesDefenceRoute: IndustriesDefenceRoute,
  IndustriesElectronicsRoute: IndustriesElectronicsRoute,
  IndustriesEnergyRoute: IndustriesEnergyRoute,
  IndustriesIndustrialEquipmentRoute: IndustriesIndustrialEquipmentRoute,
  IndustriesMedicalRoute: IndustriesMedicalRoute,
  IndustriesOilAndGasRoute: IndustriesOilAndGasRoute,
  IndustriesRoboticsRoute: IndustriesRoboticsRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

interface MaterialsRouteChildren {
  MaterialsAbsRoute: typeof MaterialsAbsRoute
  MaterialsAluminumRoute: typeof MaterialsAluminumRoute
  MaterialsBrassRoute: typeof MaterialsBrassRoute
  MaterialsBronzeRoute: typeof MaterialsBronzeRoute
  MaterialsCopperRoute: typeof MaterialsCopperRoute
  MaterialsDelrinRoute: typeof MaterialsDelrinRoute
  MaterialsDieCastingRoute: typeof MaterialsDieCastingRoute
  MaterialsMildSteelRoute: typeof MaterialsMildSteelRoute
  MaterialsNylonRoute: typeof MaterialsNylonRoute
  MaterialsPeekRoute: typeof MaterialsPeekRoute
  MaterialsPolycarbonateRoute: typeof MaterialsPolycarbonateRoute
  MaterialsStainlessSteelRoute: typeof MaterialsStainlessSteelRoute
  MaterialsTitaniumRoute: typeof MaterialsTitaniumRoute
  MaterialsToolSteelRoute: typeof MaterialsToolSteelRoute
  MaterialsIndexRoute: typeof MaterialsIndexRoute
}

const MaterialsRouteChildren: MaterialsRouteChildren = {
  MaterialsAbsRoute: MaterialsAbsRoute,
  MaterialsAluminumRoute: MaterialsAluminumRoute,
  MaterialsBrassRoute: MaterialsBrassRoute,
  MaterialsBronzeRoute: MaterialsBronzeRoute,
  MaterialsCopperRoute: MaterialsCopperRoute,
  MaterialsDelrinRoute: MaterialsDelrinRoute,
  MaterialsDieCastingRoute: MaterialsDieCastingRoute,
  MaterialsMildSteelRoute: MaterialsMildSteelRoute,
  MaterialsNylonRoute: MaterialsNylonRoute,
  MaterialsPeekRoute: MaterialsPeekRoute,
  MaterialsPolycarbonateRoute: MaterialsPolycarbonateRoute,
  MaterialsStainlessSteelRoute: MaterialsStainlessSteelRoute,
  MaterialsTitaniumRoute: MaterialsTitaniumRoute,
  MaterialsToolSteelRoute: MaterialsToolSteelRoute,
  MaterialsIndexRoute: MaterialsIndexRoute,
}

const MaterialsRouteWithChildren = MaterialsRoute._addFileChildren(
  MaterialsRouteChildren,
)

interface ResourcesRouteChildren {
  ResourcesDesignForMachiningToolkitRoute: typeof ResourcesDesignForMachiningToolkitRoute
  ResourcesDesignTipsRoute: typeof ResourcesDesignTipsRoute
  ResourcesProductLifeCycleRoute: typeof ResourcesProductLifeCycleRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesDesignForMachiningToolkitRoute:
    ResourcesDesignForMachiningToolkitRoute,
  ResourcesDesignTipsRoute: ResourcesDesignTipsRoute,
  ResourcesProductLifeCycleRoute: ResourcesProductLifeCycleRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface ServicesCncMachiningRouteChildren {
  ServicesCncMachiningCncMillingRoute: typeof ServicesCncMachiningCncMillingRoute
  ServicesCncMachiningCncTurningRoute: typeof ServicesCncMachiningCncTurningRoute
}

const ServicesCncMachiningRouteChildren: ServicesCncMachiningRouteChildren = {
  ServicesCncMachiningCncMillingRoute: ServicesCncMachiningCncMillingRoute,
  ServicesCncMachiningCncTurningRoute: ServicesCncMachiningCncTurningRoute,
}

const ServicesCncMachiningRouteWithChildren =
  ServicesCncMachiningRoute._addFileChildren(ServicesCncMachiningRouteChildren)

interface ServicesDieCastingRouteChildren {
  ServicesDieCastingQualityRoute: typeof ServicesDieCastingQualityRoute
}

const ServicesDieCastingRouteChildren: ServicesDieCastingRouteChildren = {
  ServicesDieCastingQualityRoute: ServicesDieCastingQualityRoute,
}

const ServicesDieCastingRouteWithChildren =
  ServicesDieCastingRoute._addFileChildren(ServicesDieCastingRouteChildren)

interface ServicesRouteChildren {
  Services3dScanningRoute: typeof Services3dScanningRoute
  ServicesCadCamDesignRoute: typeof ServicesCadCamDesignRoute
  ServicesCncMachiningRoute: typeof ServicesCncMachiningRouteWithChildren
  ServicesCustomManufacturingRoute: typeof ServicesCustomManufacturingRoute
  ServicesDieCastingRoute: typeof ServicesDieCastingRouteWithChildren
  ServicesInjectionMoldManufacturingRoute: typeof ServicesInjectionMoldManufacturingRoute
  ServicesLedLightsRoute: typeof ServicesLedLightsRoute
  ServicesPlasticInjectionMoldingRoute: typeof ServicesPlasticInjectionMoldingRoute
  ServicesPrecisionComponentsRoute: typeof ServicesPrecisionComponentsRoute
  ServicesProductDevelopmentRoute: typeof ServicesProductDevelopmentRoute
  ServicesProductionRoute: typeof ServicesProductionRoute
  ServicesRapidPrototypingRoute: typeof ServicesRapidPrototypingRoute
  ServicesReverseEngineeringRoute: typeof ServicesReverseEngineeringRoute
  ServicesSurfaceGrindingRoute: typeof ServicesSurfaceGrindingRoute
  ServicesToolAndDieRoute: typeof ServicesToolAndDieRoute
  ServicesWireEdmRoute: typeof ServicesWireEdmRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  Services3dScanningRoute: Services3dScanningRoute,
  ServicesCadCamDesignRoute: ServicesCadCamDesignRoute,
  ServicesCncMachiningRoute: ServicesCncMachiningRouteWithChildren,
  ServicesCustomManufacturingRoute: ServicesCustomManufacturingRoute,
  ServicesDieCastingRoute: ServicesDieCastingRouteWithChildren,
  ServicesInjectionMoldManufacturingRoute:
    ServicesInjectionMoldManufacturingRoute,
  ServicesLedLightsRoute: ServicesLedLightsRoute,
  ServicesPlasticInjectionMoldingRoute: ServicesPlasticInjectionMoldingRoute,
  ServicesPrecisionComponentsRoute: ServicesPrecisionComponentsRoute,
  ServicesProductDevelopmentRoute: ServicesProductDevelopmentRoute,
  ServicesProductionRoute: ServicesProductionRoute,
  ServicesRapidPrototypingRoute: ServicesRapidPrototypingRoute,
  ServicesReverseEngineeringRoute: ServicesReverseEngineeringRoute,
  ServicesSurfaceGrindingRoute: ServicesSurfaceGrindingRoute,
  ServicesToolAndDieRoute: ServicesToolAndDieRoute,
  ServicesWireEdmRoute: ServicesWireEdmRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CapabilitiesRoute: CapabilitiesRoute,
  CareersRoute: CareersRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  CertificationsRoute: CertificationsRoute,
  ContactRoute: ContactRoute,
  DownloadsRoute: DownloadsRoute,
  EquipmentRoute: EquipmentRoute,
  FactoryRoute: FactoryRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  MaterialsRoute: MaterialsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRoute,
  PrototypingToProductionRoute: PrototypingToProductionRoute,
  QualityRoute: QualityRoute,
  QuoteRoute: QuoteRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
